CREATE USER IF NOT EXISTS cities;

CREATE DATABASE IF NOT EXISTS cities;
GRANT ALL PRIVILEGES ON cities.* TO cities;

CREATE DATABASE IF NOT EXISTS test_cities;
GRANT ALL PRIVILEGES ON test_cities.* TO cities;
